language: node_js
node_js:
- 4.2.1
sudo: false
before_install:
- chmod 755 ./deploy.sh
script: npm run build
after_success: ./deploy.sh
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true