language: node_js
node_js:
- 4.2.1
sudo: false
before_install:
- chmod 755 ./scripts/build.sh
- chmod 755 ./scripts/deploy.sh
script: npm run build
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true