language: node_js
node_js:
- 6.9.5
sudo: false
install: npm --production=false install
script: npm run build:prod
before_deploy:
- chmod 755 ./scripts/deploy.sh
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true